spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:authservice_dev}
    username: ${POSTGRES_USER:dev_user}
    password: ${POSTGRES_PASSWORD:dev_pass}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: "optional:file:.env"